version: "3.7"
services:
  strapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: strapi
    container_name: strapi
    working_dir: /opt/app
    env_file: .env
    command: ./cmd.sh
    volumes:
      - ./:/opt/app
    ports:
      - "1337:1337"
    networks:
      - default
    depends_on:
      - database

  database:
    container_name: strapi_db
    platform: linux/amd64
    env_file: .env
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      LANG: C.UTF_8
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
        - default

volumes:
  data:

networks:
  default:
    driver: bridge
